language: python
python:
  - "3.6"
  - "pypy3.5"
services:
  - postgresql
#addons:
#  postgresql: "9.6"
install: # PENDING coveralls以外 setup.pyへ？
  - pip install psycopg2
  - pip install coveralls 
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - coverage run --branch --source=niascape tests
  - coverage report -m
after_success:
  coveralls --verbose
notifications:
  slack: ayziao:XBzPkkUkRCa4pU2b9yQSFsW3
