language: python
python:
  - "3.4"
  - pypy3
install:
  - pip install coveralls --use-mirrors
script:
  - coverage run --branch --source=niascape tests/test_main.py
  - coverage report -m
after_success:
  coveralls --verbose
