language: python
python:
  - "3.6"
#  - pypy3
install:
  - pip install coveralls 
script:
  - coverage run --branch --source=niascape tests/all_test.py
  - coverage report -m
after_success:
  coveralls --verbose
