language: python
python:
  - "3.6"
#  - pypy3
install:
  - pip install coveralls 
script:
  - coverage run --branch --source=niascape tests
  - coverage report -m
after_success:
  coveralls --verbose
notifications:
    slack: ayziao:XBzPkkUkRCa4pU2b9yQSFsW3
